---
- name: Run backup
  hosts: all
  become: true

  tasks:
    - name: Execute backup script
      command: "sudo -u {{ app_user }} {{ app_base_path }}/scripts/backup.sh"
      register: backup_result

    - name: Show backup output
      debug:
        var: backup_result.stdout_lines
