---
- name: Run backup
  hosts: all
  become: true

  tasks:
    - name: Execute backup script
      command: "{{ app_base_path }}/scripts/backup.sh"
      become: true
      become_user: "{{ app_user }}"
      register: backup_result

    - name: Show backup output
      debug:
        var: backup_result.stdout_lines
